function test_sign_up() {
	var client = windmill.jsTest.actions;
	client.open('http://localhost:5985/hejhej_test/_design/hejhej/index.html');
	client.click({id: 'sign_up'});
	client.asserts.assertText({id: 'sign_up'}, 'Sign Up');
	//windmill.jsTest.actions.click({ text: 'Sign Up' });
};

// Generated by the windmill services transformer
var test_users_test = new function() {
    this.test_actions = [
{"params": {"url": "http://localhost:5985/hejhej_test/_design/hejhej/index.html"}, "method": "open"},
{"params": {"link": "Sign Up"}, "method": "click"},
{"params": {"id": "username"}, "method": "click"},
{"params": {"text": "alexx", "id": "username"}, "method": "type"},
{"params": {"text": "test", "id": "password"}, "method": "type"},
{"params": {"text": "test", "id": "password_confirmation"}, "method": "type"},
{"params": {"value": "Sign Up"}, "method": "click"},
{"params": {"xpath": "//h1", "validator": "Welcome alexx"}, "method": "asserts.assertText"}
    ];
}


// When I go to the start page
//   And I follow "Sign Up"
//   And I fill in "Username" with "alex"
//   And I fill in "Password" with "test"
//   And I fill in "Password Confirmation" with "test"
//   And I press "Sign Up"
// Then I should see "Welcome alex"
